# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openneko < Formula
  desc "OpenNeko operator CLI — supervises the stack and manages plugins"
  homepage "https://getneko.app"
  version "1.13.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-neko/neko/releases/download/v1.13.2/openneko_1.13.2_darwin_amd64.tar.gz"
      sha256 "537775a9a0cd0aae7cced2e0624ee98be3e003a37667155b15387982b978e04c"

      define_method(:install) do
        bin.install "openneko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-neko/neko/releases/download/v1.13.2/openneko_1.13.2_darwin_arm64.tar.gz"
      sha256 "8bb10078a8a406d8664874557952ab4080d851a94632d23c718dc688606af36d"

      define_method(:install) do
        bin.install "openneko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-neko/neko/releases/download/v1.13.2/openneko_1.13.2_linux_amd64.tar.gz"
      sha256 "11babb9efee8080cf1a8283599565b1d3a9dc3395afafee6e20d7a71ef487212"
      define_method(:install) do
        bin.install "openneko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-neko/neko/releases/download/v1.13.2/openneko_1.13.2_linux_arm64.tar.gz"
      sha256 "afc2fcfab0ba12fb59164b0419b7064de4a96074462a0bb955899a1a386ecb67"
      define_method(:install) do
        bin.install "openneko"
      end
    end
  end

  def caveats
    <<~EOS
      OpenNeko needs Docker. Install Docker Desktop (macOS) or Docker Engine (Linux) first.
      `openneko start` materializes its compose file under .openneko/runtime/ in the
      current directory; run it from a working dir you control.
    EOS
  end

  test do
    system "#{bin}/openneko", "version"
  end
end
