# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openneko < Formula
  desc "OpenNeko operator CLI — supervises the stack and manages plugins"
  homepage "https://getneko.app"
  version "1.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-neko/neko/releases/download/v1.13.0/openneko_1.13.0_darwin_amd64.tar.gz"
      sha256 "a1ca38889a849638066e74fae1a7f22cc563aa4d98af24771c89d72ed6d76cad"

      define_method(:install) do
        bin.install "openneko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-neko/neko/releases/download/v1.13.0/openneko_1.13.0_darwin_arm64.tar.gz"
      sha256 "b991aeaf76791acc9693abd886f45f81d5094aa7389c2c2000de48b054bf6514"

      define_method(:install) do
        bin.install "openneko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-neko/neko/releases/download/v1.13.0/openneko_1.13.0_linux_amd64.tar.gz"
      sha256 "c3188d61f97637857ba3321ae03f129a2d08281d46f171d546b6b86ccbbc8ab4"
      define_method(:install) do
        bin.install "openneko"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-neko/neko/releases/download/v1.13.0/openneko_1.13.0_linux_arm64.tar.gz"
      sha256 "72e8955d917d8abf1bec25069a3bac1609c2a02033e96773b13ce0a8543c939d"
      define_method(:install) do
        bin.install "openneko"
      end
    end
  end

  def caveats
    <<~EOS
      OpenNeko needs Docker. Install Docker Desktop (macOS) or Docker Engine (Linux) first.
      `openneko start` materializes its compose file under .openneko/runtime/ in the
      current directory; run it from a working dir you control.
    EOS
  end

  test do
    system "#{bin}/openneko", "version"
  end
end
