# This file was generated by GoReleaser. DO NOT EDIT.
cask "openneko" do
  version "2.39.1"

  on_macos do
    on_arm do
      sha256 "dc21f85565ca59495ade3c77ab2c4052e4e8b50e370efd32fa2200e0ede2b5c5"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "722eab544f7bac86d3d850cd1d4db23119b2a471dcf92ca765ae4facc2eadb0b"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "da3d2f5964eda3424d23e6fcf41fc770c5c37952603b770b7b343adcb3a2298a"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e479ed1ddb20b3bec26ca6bf72a2fda0e6830a0781bf98f21055dbee603b341"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_amd64.tar.gz"
    end
  end

  name "openneko"
  desc "OpenNeko operator CLI — supervises the stack and manages plugins"
  homepage "https://openneko.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openneko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openneko"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    OpenNeko needs Docker. Install Docker Desktop (macOS) or Docker Engine (Linux) first.
    `openneko start` materializes its compose file under .openneko/runtime/ in the
    current directory; run it from a working dir you control.
  EOS
end
