# This file was generated by GoReleaser. DO NOT EDIT.
cask "openneko" do
  version "2.4.0"

  on_macos do
    on_intel do
      sha256 "adc6e65c9189bd8b3b0b7d46aa028874cf949eab5686e5853400c8e9acdd2711"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab967f7ec6774c5854c67df13be7f4dd5b3c6822ab3f207df7333d71a4f88d03"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e9b62d556a00441434a72a9ad1519be065aa07330014cae5f719bdb7db49af3"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "59b9ceef4b7ba1372d1c9807834cdece478d550ca38401e37cb96ca8a919d82e"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openneko"
  desc "OpenNeko operator CLI — supervises the stack and manages plugins"
  homepage "https://openneko.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openneko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openneko"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    OpenNeko needs Docker. Install Docker Desktop (macOS) or Docker Engine (Linux) first.
    `openneko start` materializes its compose file under .openneko/runtime/ in the
    current directory; run it from a working dir you control.
  EOS
end
