# This file was generated by GoReleaser. DO NOT EDIT.
cask "openneko" do
  version "2.29.2"

  on_macos do
    on_intel do
      sha256 "9471da58ec7dce64bbeb5f62cf0e4ebcbbef5c1c6fc42629be4fe5dbcb386152"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a592d2fdc8a7e1d3941fa36b94c83362afc260da4fc6526630d63ef85d87f6c"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c2cb3117fed22bf11f416025706d73b40d46730918c0112fc8555bdcf87a889b"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a207afca4b46eeccc7c6b2a278ae5a8b0a3054284695844f845fb1e009aa959"
      url "https://github.com/open-neko/openneko/releases/download/v#{version}/openneko_#{version}_linux_arm64.tar.gz"
    end
  end

  name "openneko"
  desc "OpenNeko operator CLI — supervises the stack and manages plugins"
  homepage "https://openneko.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openneko"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openneko"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    OpenNeko needs Docker. Install Docker Desktop (macOS) or Docker Engine (Linux) first.
    `openneko start` materializes its compose file under .openneko/runtime/ in the
    current directory; run it from a working dir you control.
  EOS
end
